# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-JA-Mail
version:      0.03
version_from: Mail.pm
installdirs:  site
requires:
    Encode:                        2.10
    MIME::Base64:                  3.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
